export const QUERY_KEYS = {
  PROFILE: {
    GET_MY_USER_PROFILE: "GET_MY_USER_PROFILE",
    GET_USER_PROFILE: "GET_USER_PROFILE",
  },
  FRIEND: {
    GET_MY_FRIENDS: "GET_MY_FRIENDS",
    GET_MY_HIDEEN_FRIENDS: "GET_MY_HIDEEN_FRIENDS",
    GET_MY_BLOCKED_FRIENDS: "GET_MY_BLOCKED_FRIENDS",

    GET_FRIEND: "GET_FRIEND",
  },
  CHATTING: {
    GET_CHAATING_MESSAGES: "GET_CHAATING_MESSAGES",
    GET_CHATTING_ROOM_INFO: "GET_CHATTING_ROOM_INFO",
  },
};
