export enum QUERY_KEYS {
  GET_MY_USER_PROFILE = "GET_MY_USER_PROFILE",
  GET_USER_PROFILE = "GET_USER_PROFILE",

  GET_MY_FRIENDS = "GET_MY_FRIENDS",
  GET_MY_HIDEEN_FRIENDS = "GET_MY_HIDEEN_FRIENDS",
  GET_MY_BLOCKED_FRIENDS = "GET_MY_BLOCKED_FRIENDS",
}
